import * as fs from "fs";
import * as path from "path";
import type { FileState, FileLineEnding } from "./state";

export type FileReadMetadata = {
  content: string;
  encoding: BufferEncoding;
  lineEndings: FileLineEnding;
  timestamp: number;
};

export function normalizeContent(value: string): string {
  return value.replace(/\r\n/g, "\n");
}

export function detectLineEndings(value: string): FileLineEnding {
  return value.includes("\r\n") ? "CRLF" : "LF";
}

export function detectEncoding(buffer: Buffer): BufferEncoding {
  if (buffer.length >= 2 && buffer[0] === 0xff && buffer[1] === 0xfe) {
    return "utf16le";
  }

  return "utf8";
}

export function readTextFileWithMetadata(filePath: string): FileReadMetadata {
  const buffer = fs.readFileSync(filePath);
  const stat = fs.statSync(filePath);
  const encoding = detectEncoding(buffer);
  const raw = buffer.toString(encoding);

  return {
    content: normalizeContent(raw),
    encoding,
    lineEndings: detectLineEndings(raw),
    timestamp: Math.floor(stat.mtimeMs),
  };
}

export function writeTextFile(
  filePath: string,
  content: string,
  encoding: BufferEncoding,
  lineEndings: FileLineEnding
): number {
  const normalized = normalizeContent(content);
  const toWrite = lineEndings === "CRLF" ? normalized.replace(/\n/g, "\r\n") : normalized;
  fs.writeFileSync(filePath, toWrite, { encoding });
  return Buffer.byteLength(toWrite, encoding === "utf16le" ? "utf16le" : "utf8");
}

export function ensureParentDirectory(filePath: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

export function hasFileChangedSinceState(filePath: string, state: FileState): boolean {
  const current = readTextFileWithMetadata(filePath);
  if (current.timestamp <= state.timestamp) {
    return false;
  }

  const isFullRead = !state.isPartialView && typeof state.offset === "undefined" && typeof state.limit === "undefined";

  return !(isFullRead && current.content === state.content);
}

export function buildDiffPreview(
  filePath: string,
  originalContent: string | null,
  updatedContent: string,
  maxLines = 40
): string | null {
  const original = originalContent === null ? null : normalizeContent(originalContent);
  const updated = normalizeContent(updatedContent);

  if (original !== null && original === updated) {
    return null;
  }

  const oldLines = toDiffLines(original);
  const newLines = toDiffLines(updated);

  let prefix = 0;
  while (prefix < oldLines.length && prefix < newLines.length && oldLines[prefix] === newLines[prefix]) {
    prefix += 1;
  }

  let suffix = 0;
  while (
    suffix < oldLines.length - prefix &&
    suffix < newLines.length - prefix &&
    oldLines[oldLines.length - 1 - suffix] === newLines[newLines.length - 1 - suffix]
  ) {
    suffix += 1;
  }

  const oldChanged = oldLines.slice(prefix, oldLines.length - suffix);
  const newChanged = newLines.slice(prefix, newLines.length - suffix);
  const oldStart = original === null ? 0 : prefix + 1;
  const newStart = prefix + 1;

  const previewLines = [
    `--- ${original === null ? "/dev/null" : `a/${filePath}`}`,
    `+++ b/${filePath}`,
    `@@ -${oldStart},${oldChanged.length} +${newStart},${newChanged.length} @@`,
  ];

  if (prefix > 0) {
    previewLines.push(` ${oldLines[prefix - 1]}`);
  }

  for (const line of oldChanged) {
    previewLines.push(`-${line}`);
  }

  for (const line of newChanged) {
    previewLines.push(`+${line}`);
  }

  if (suffix > 0) {
    previewLines.push(` ${oldLines[oldLines.length - suffix]}`);
  }

  if (previewLines.length > maxLines) {
    return `${previewLines.slice(0, maxLines).join("\n")}\n...`;
  }

  return previewLines.join("\n");
}

function toDiffLines(content: string | null): string[] {
  if (!content) {
    return [];
  }

  const lines = content.split("\n");
  if (lines[lines.length - 1] === "") {
    lines.pop();
  }
  return lines;
}

/**
 * Apply a unified diff generated by {@link buildDiffPreview} in reverse
 * to the file at `filePath`.
 *
 * The diff maps the *current* file content back to the *target* content
 * (i.e. the "old" side = current, "new" side = target).
 *
 * Returns `true` on success, `false` if the patch could not be applied
 * (e.g. the file no longer matches the expected state).
 */
export function applyUnifiedDiff(filePath: string, diff: string): boolean {
  const content = fs.readFileSync(filePath, "utf8");
  const normalized = content.replace(/\r\n/g, "\n");

  const lines = diff.split("\n");

  // Parse hunk: skip header lines (---, +++, @@)
  let i = 0;
  // Skip ---
  if (i < lines.length && lines[i]!.startsWith("---")) i++;
  // Skip +++
  if (i < lines.length && lines[i]!.startsWith("+++")) i++;
  // Parse hunk header: @@ -os,oc +ns,nc @@
  if (i >= lines.length) return false;
  const hunkMatch = lines[i]!.match(/^@@ -(\d+),(\d+) \+(\d+),(\d+) @@/);
  if (!hunkMatch) return false;
  i++;

  // Collect old lines (starting with '-'), new lines (starting with '+'),
  // and context lines (starting with ' ').
  const oldLines: string[] = [];
  const newLines: string[] = [];
  const prefixContextLines: string[] = [];
  const suffixContextLines: string[] = [];

  // Phase: collect prefix context (before first '-' or '+')
  while (i < lines.length && lines[i]!.startsWith(" ")) {
    prefixContextLines.push(lines[i]!.slice(1));
    i++;
  }

  // Phase: collect old lines
  while (i < lines.length && lines[i]!.startsWith("-")) {
    oldLines.push(lines[i]!.slice(1));
    i++;
  }

  // Phase: collect new lines
  while (i < lines.length && lines[i]!.startsWith("+")) {
    newLines.push(lines[i]!.slice(1));
    i++;
  }

  // Phase: collect suffix context
  while (i < lines.length && lines[i]!.startsWith(" ")) {
    suffixContextLines.push(lines[i]!.slice(1));
    i++;
  }

  if (oldLines.length === 0 && newLines.length === 0) {
    return false;
  }

  // Build search pattern and replacement.
  const searchBlock = [...prefixContextLines, ...oldLines, ...suffixContextLines];
  const replaceBlock = [...prefixContextLines, ...newLines, ...suffixContextLines];

  // Search in the file (join with \n to find multi-line block).
  const searchStr = searchBlock.join("\n");
  const replaceStr = replaceBlock.join("\n");

  // If the search block is empty (edge case), skip.
  if (searchStr.length === 0) return false;

  const pos = normalized.indexOf(searchStr);
  if (pos === -1) return false;

  const updated = normalized.slice(0, pos) + replaceStr + normalized.slice(pos + searchStr.length);

  // Preserve trailing newline if original content had one and updated doesn't.
  const preserved = content.endsWith("\n") && !updated.endsWith("\n") ? updated + "\n" : updated;
  fs.writeFileSync(filePath, preserved, "utf8");
  return true;
}
